export const SET_MESSAGE = "SET_MESSAGE";
export const SET_MOBILE_NAVBAR = "SET_MOBILE_NAVBAR";

export const SET_SELECTED_PAGE = "SET_SELECTED_PAGE";
export const SET_LOGINSTATUS = "SET_LOGINSTATUS";
export const SET_AUTH_FIELDS = "SET_AUTH_FIELDS";

export const SET_PROFILE_FIELDS = "SET_PROFILE_FIELDS";
export const SET_PROFILE = "SET_PROFILE";
export const SET_EDITABLE = "SET_EDITABLE";
export const SET_RESET_PASSWORD_MODAL = "SET_RESET_PASSWORD_MODAL";

export const SET_COURSES_FIELDS = "SET_COURSES_FIELDS";
export const SET_COURSES_LIST = "SET_COURSES_LIST";
export const SET_ADD_COURSES_MODAL = "SET_ADD_COURSES_MODAL";
export const SET_DELETE_COURSES_MODAL = "SET_DELETE_COURSES_MODAL";
export const SET_EDIT_MODAL = "SET_EDIT_MODAL";
export const SET_SELECTED_COURSE = "SET_SELECTED_COURSE";
export const SET_COURSES_LOADING = "SET_COURSES_LOADING";
