export const SET_MESSAGE = "SET_MESSAGE";

export const SET_SELECTED_PAGE = "SET_SELECTED_PAGE";
export const SET_LOGINSTATUS = "SET_LOGINSTATUS";
export const SET_AUTH_FIELDS = "SET_AUTH_FIELDS";

export const SET_PROFILE_FIELDS = "SET_PROFILE_FIELDS";
export const SET_PROFILE = "SET_PROFILE";
export const SET_EDITABLE = "SET_EDITABLE";
export const SET_RESET_PASSWORD_MODAL = "SET_RESET_PASSWORD_MODAL";
